name: Daily Update from Dark Visitors
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  dark-visitors:
    runs-on: ubuntu-latest
    name: dark-visitors
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - run: |
          pip install beautifulsoup4 requests
          git config --global user.name "dark-visitors"
          git config --global user.email "dark-visitors@users.noreply.github.com"
          python code/dark_visitors.py
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Daily update from Dark Visitors" && git push)
        shell: bash